void serial_print() {
  if (serialflag == 1) {
    //    String sendvalue = "datetime=20";
    //    sendvalue += int(year);
    //    sendvalue += ".";
    //    sendvalue += int(month);
    //    sendvalue += ".";
    //    sendvalue += int(date);
    //    sendvalue += ".%20";
    //    sendvalue += int(hours);
    //    sendvalue += ":";
    //    sendvalue += int(minutes);
    //    sendvalue += ":";
    //    sendvalue += int(seconds);
    //    sendvalue += "&room_t=";
    //    sendvalue += int(floor(room_t));
    //    sendvalue += ".";
    //    sendvalue += int((room_t - int(floor(room_t))) * 100);
    //    sendvalue += "&room_h=";
    //    sendvalue += int(floor(room_h));
    //    sendvalue += ".";
    //    sendvalue += int((room_h - int(floor(room_h))) * 100);
    //    sendvalue += "&room_hic=";
    //    sendvalue += int(floor(room_hic));
    //    sendvalue += ".";
    //    sendvalue += int((room_hic - int(floor(room_hic))) * 100);
    //    sendvalue += "&room_index=";
    //    sendvalue += int(floor(room_index));
    //    sendvalue += ".";
    //    sendvalue += int((room_index - int(floor(room_index))) * 100);
    //    sendvalue += "&room_lux=";
    //    sendvalue += int(floor(room_lux));
    //    sendvalue += ".";
    //    sendvalue += int((room_lux - int(floor(room_lux))) * 100);
    //    sendvalue += "&detect=";
    //    sendvalue += detect;
    //    sendvalue += "&window_s=";
    //    sendvalue += EEPROM.read(6);
    //    sendvalue += "&window_l=";
    //    sendvalue += window_l;
    //    sendvalue += "&window_e=";
    //    sendvalue += EEPROM.read(7);
    //    sendvalue += "&window_v=";
    //    sendvalue += int(floor(window_v));
    //    sendvalue += ".";
    //    sendvalue += int((window_v - int(floor(window_v))) * 100);
    //    sendvalue += "&window_ov=";
    //    sendvalue += EEPROM.read(8);
    //    sendvalue += ".";
    //    sendvalue += EEPROM.read(9);
    //    sendvalue += "&outdoor_t=";
    //    sendvalue += int(floor(outdoor_t));
    //    sendvalue += ".";
    //    sendvalue += int((outdoor_t - int(floor(outdoor_t))) * 100);
    //    sendvalue += "&outdoor_h=";
    //    sendvalue += int(floor(outdoor_h));
    //    sendvalue += ".";
    //    sendvalue += int((outdoor_h - int(floor(outdoor_h))) * 100);
    //    sendvalue += "&outdoor_hic=";
    //    sendvalue += int(floor(outdoor_hic));
    //    sendvalue += ".";
    //    sendvalue += int((outdoor_hic - int(floor(outdoor_hic))) * 100);
    //    sendvalue += "&outdoor_index=";
    //    sendvalue += int(floor(outdoor_index));
    //    sendvalue += ".";
    //    sendvalue += int((outdoor_index - int(floor(outdoor_index))) * 100);
    //    sendvalue += "&pad_s=";
    //    sendvalue += EEPROM.read(2);
    //    sendvalue += "&pad_r=";
    //    sendvalue += digitalRead(heatrelay);
    //    sendvalue += "&pad_t=";
    //    sendvalue += int(floor(pad_t));
    //    sendvalue += ".";
    //    sendvalue += int((pad_t - int(floor(pad_t))) * 100);
    //    sendvalue += "&pad_h=";
    //    sendvalue += int(floor(pad_h));
    //    sendvalue += ".";
    //    sendvalue += int((pad_h - int(floor(pad_h))) * 100);
    //    sendvalue += "&pad_hic=";
    //    sendvalue += int(floor(pad_hic));
    //    sendvalue += ".";
    //    sendvalue += int((pad_hic - int(floor(pad_hic))) * 100);
    //    sendvalue += "&pad_low=";
    //    sendvalue += EEPROM.read(0);
    //    sendvalue += "&pad_high=";
    //    sendvalue += EEPROM.read(1);
    //    sendvalue += "&boiler_s=";
    //    sendvalue += EEPROM.read(5);
    //    sendvalue += "&boiler_r=";
    //    sendvalue += digitalRead(boilerrelay);
    //    sendvalue += "&boiler_t=";
    //    sendvalue += int(floor(boiler_t));
    //    sendvalue += ".";
    //    sendvalue += int((boiler_t - int(floor(boiler_t))) * 100);
    //    sendvalue += "&boiler_h=";
    //    sendvalue += int(floor(boiler_h));
    //    sendvalue += ".";
    //    sendvalue += int((boiler_h - int(floor(boiler_h))) * 100);
    //    sendvalue += "&boiler_low=";
    //    sendvalue += EEPROM.read(3);
    //    sendvalue += "&boiler_high=";
    //    sendvalue += EEPROM.read(4);
    //    sendvalue += "&gas5=";
    //    sendvalue += int(floor(gas5.readSensor()));
    //    sendvalue += ".";
    //    sendvalue += int((gas5.readSensor() - int(floor(gas5.readSensor()))) * 100);
    //    sendvalue += "&boiler5=";
    //    sendvalue += int(floor(boiler5.readSensor()));
    //    sendvalue += ".";
    //    sendvalue += int((boiler5.readSensor() - int(floor(boiler5.readSensor()))) * 100);
    //    sendvalue += "&gas7=";
    //    sendvalue += int(floor(gas7.readSensor()));
    //    sendvalue += ".";
    //    sendvalue += int((gas7.readSensor() - int(floor(gas7.readSensor()))) * 100);
    //    sendvalue += "&boiler7=";
    //    sendvalue += int(floor(boiler7.readSensor()));
    //    sendvalue += ".";
    //    sendvalue += int((boiler7.readSensor() - int(floor(boiler7.readSensor()))) * 100);
    //    sendvalue += "&roomtemp=";
    //    sendvalue += roomtemp;
    //    sendvalue += "&roomhumi=";
    //    sendvalue += roomhumi;
    //    sendvalue += "&roomhic=";
    //    sendvalue += roomhic;
    //    sendvalue += "&roomindex=";
    //    sendvalue += roomindex;
    //    sendvalue += "&roomlux=";
    //    sendvalue += roomlux;
    //    sendvalue += "&outdoortemp=";
    //    sendvalue += outdoortemp;
    //    sendvalue += "&outdoorhumi=";
    //    sendvalue += outdoorhumi;
    //    sendvalue += "&outdoorhic=";
    //    sendvalue += outdoorhic;
    //    sendvalue += "&outdoorindex=";
    //    sendvalue += outdoorindex;
    //    sendvalue += "&padtemp=";
    //    sendvalue += padtemp;
    //    sendvalue += "&padhumi=";
    //    sendvalue += padhumi;
    //    sendvalue += "&padhic=";
    //    sendvalue += padhic;
    //    sendvalue += "&boilertemp=";
    //    sendvalue += boilertemp;
    //    sendvalue += "&boilerhumi=";
    //    sendvalue += boilerhumi;
    //    sendvalue += " HTTP/1.1";
    //    Serial.println(sendvalue);
    //    Serial.print("Content-Length: ");
    //    Serial.println(sendvalue.length());

    //    Serial.print("20");
    //    if (year < 10) {
    //      Serial.print("0");
    //    }
    //    Serial.print(year, DEC);
    //    Serial.print(" / ");
    //    if (month < 10) {
    //      Serial.print("0");
    //    }
    //    Serial.print(month, DEC);
    //    Serial.print(" / ");
    //    if (date < 10) {
    //      Serial.print("0");
    //    }
    //    Serial.print(date, DEC);
    //    Serial.print("\t");
    //    if (hours < 10) {
    //      Serial.print("0");
    //    }
    //    Serial.print(hours, DEC);
    //    Serial.print(" : ");
    //    if (minutes < 10) {
    //      Serial.print("0");
    //    }
    //    Serial.print(minutes, DEC);
    //    Serial.print(" : ");
    //    if (seconds < 10) {
    //      Serial.print("0");
    //    }
    //    Serial.print(seconds, DEC);
    //    Serial.println();
    //    Serial.print("RoomDHT(41): ");
    //    Serial.print(room_dht1.readTemperature(), 1);
    //    Serial.print(" c");
    //    Serial.print("\tRoomDHT(42): ");
    //    Serial.print(room_dht2.readTemperature(), 1);
    //    Serial.print(" c");
    //    Serial.print("\tRoomDHT(43): ");
    //    Serial.print(room_dht3.readTemperature(), 1);
    //    Serial.print(" c");
    //    Serial.print("\tRoomDHT(44): ");
    //    Serial.print(room_dht4.readTemperature(), 1);
    //    Serial.print(" c");
    //    Serial.print("\tPadDHT(46): ");
    //    Serial.print(pad_dht1.readTemperature(), 1);
    //    Serial.print(" c");
    //    Serial.print("\tOutdoorDHT(47): ");
    //    Serial.print(outdoor_dht1.readTemperature(), 1);
    //    Serial.print(" c");
    //    Serial.print("\tSENDVALUE: ");
    //    Serial.print(int(outdoor_t));
    //    Serial.print(".");
    //    if (int((outdoor_t - int(outdoor_t)) * 10) < 0)
    //      Serial.print(int((outdoor_t - int(outdoor_t)) * -10));
    //    else
    //      Serial.print(int((outdoor_t - int(outdoor_t)) * 10));
    //    Serial.print(" c");
    //        Serial.print("\tOutdoorDHT(48): ");
    //        Serial.print(outdoor_dht2.readTemperature(), 1);
    //        Serial.print(" c");
    //    Serial.println();
    //    Serial.print("BoilerDHT(40): ");
    //    Serial.print(boiler_dht1.readHumidity(), 1);
    //    Serial.print(" %");
    //    Serial.print("\tRoomDHT(41): ");
    //    Serial.print(room_dht1.readHumidity(), 1);
    //    Serial.print(" %");
    //    Serial.print("\tRoomDHT(42): ");
    //    Serial.print(room_dht2.readHumidity(), 1);
    //    Serial.print(" %");
    //    Serial.print("\tRoomDHT(43): ");
    //    Serial.print(room_dht3.readHumidity(), 1);
    //    Serial.print(" %");
    //    Serial.print("\tRoomDHT(44): ");
    //    Serial.print(room_dht4.readHumidity(), 1);
    //    Serial.print(" %");
    //    Serial.print("\tPadDHT(46): ");
    //    Serial.print(pad_dht1.readHumidity(), 1);
    //    Serial.print(" %");
    //    Serial.print("\tOutdoorDHT(47): ");
    //    Serial.print(outdoor_dht1.readHumidity(), 1);
    //    Serial.print(" %");
    //    Serial.print("\tOutdoorDHT(48): ");
    //    Serial.print(outdoor_dht2.readHumidity(), 1);
    //    Serial.print(" %");
    //    Serial.println();
    //    Serial.println();
    //    Serial.print("Window Location: ");
    //    Serial.print(window_l);
    //    Serial.println();
    //    Serial.print("room_lux: ");
    //    Serial.print(room_lux, 1);
    //    Serial.print(" %");
    //    Serial.print("\tDETECT: ");
    //    if (detect == 1) {
    //      Serial.print("used");
    //    } else if (detect == 0) {
    //      Serial.print("not used");
    //    }
    //    Serial.println();
  }
}
